version: "3.8"

services:
  db:
    container_name: postgres
    image: postgres:16.8
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    networks:
      - postgres-0

volumes:
  postgres-data:

networks:
  postgres-0:
    driver: bridge
